# Generated by Django 2.1.5 on 2019-02-23 06:00

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncas', '0008_auto_20190215_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Topic')),
                ('descrip', models.TextField(max_length=1000, verbose_name='Details')),
                ('date_publish', models.DateField(default=datetime.datetime(2019, 2, 23, 11, 30, 6, 844833), verbose_name='Date of published')),
                ('last_date', models.DateField(verbose_name='Last date for submit')),
                ('file', models.FileField(null=True, upload_to='None/')),
                ('sub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ncas.Subject', verbose_name='Subject')),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ncas.Tutor', verbose_name='Tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Topic')),
                ('date_of_published', models.DateField(default=datetime.datetime(2019, 2, 23, 11, 30, 6, 860433), verbose_name='Date of published')),
                ('descrip', models.TextField(max_length=1000, verbose_name='Details')),
                ('fileupload', models.FileField(null=True, upload_to='notifications/')),
            ],
        ),
        migrations.AlterField(
            model_name='mark',
            name='s_mark1',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='First Internal mark'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='s_mark2',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='Second Internal mark'),
        ),
    ]
