# Generated by Django 2.1.5 on 2019-02-26 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncas', '0009_auto_20190223_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_publish',
            field=models.DateField(default=datetime.datetime(2019, 2, 26, 11, 7, 5, 17239), verbose_name='Date of published'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date_of_published',
            field=models.DateField(default=datetime.datetime(2019, 2, 26, 11, 7, 5, 17239), verbose_name='Date of published'),
        ),
    ]
