# Generated by Django 2.1.5 on 2019-02-26 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncas', '0010_auto_20190226_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Topic')),
                ('date_of_published', models.DateField(default=datetime.datetime(2019, 2, 26, 11, 11, 8, 411659), verbose_name='Date of published')),
                ('descrip', models.TextField(max_length=1000, verbose_name='Details')),
                ('fileupload', models.FileField(null=True, upload_to='notifications/')),
            ],
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_publish',
            field=models.DateField(default=datetime.datetime(2019, 2, 26, 11, 11, 8, 396059), verbose_name='Date of published'),
        ),
    ]
