# Generated by Django 2.1.5 on 2019-02-26 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncas', '0011_auto_20190226_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_publish',
            field=models.DateField(default=datetime.datetime(2019, 2, 26, 11, 59, 39, 39693), verbose_name='Date of published'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(default='noimg.png', upload_to='assignments/None/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_of_published',
            field=models.DateField(default=datetime.datetime(2019, 2, 26, 11, 59, 39, 39693), verbose_name='Date of published'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='fileupload',
            field=models.FileField(default='noimg.png', upload_to='notifications/'),
        ),
    ]
