# Generated by Django 2.1.5 on 2019-02-26 08:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncas', '0012_auto_20190226_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_publish',
            field=models.DateField(default=datetime.datetime(2019, 2, 26, 13, 59, 8, 32860), verbose_name='Date of published'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncas.Subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncas.Tutor', verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_of_published',
            field=models.DateField(default=datetime.datetime(2019, 2, 26, 13, 59, 8, 32860), verbose_name='Date of published'),
        ),
    ]
