# Generated by Django 2.1.5 on 2019-02-26 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncas', '0013_auto_20190226_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 14, 5, 31, 764662), verbose_name='Date of published'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_of_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 14, 5, 31, 764662), verbose_name='Date of published'),
        ),
    ]
