# Generated by Django 2.1.5 on 2019-02-26 08:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ncas', '0014_auto_20190226_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 8, 41, 44, 965516, tzinfo=utc), verbose_name='Date of published'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_of_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 8, 41, 44, 965516, tzinfo=utc), verbose_name='Date of published'),
        ),
    ]
