# Generated by Django 2.1.5 on 2019-02-26 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ncas', '0015_auto_20190226_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of published'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_of_published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of published'),
        ),
    ]
